// AUTO-GENERATED by logos.py - do not edit by hand. Re-run logos.py after adding/removing files in img/logos/.
window.LOGO_TAGS = ["agz", "an", "ctz", "dc", "eth", "fz", "rg", "rnx", "sh", "tc", "tsg", "wb"];
window.logoFile = function(tag) {
  var clean = String(tag).trim().replace(/[^a-zA-Z0-9_-]/g, "").toLowerCase();
  if (!clean || window.LOGO_TAGS.indexOf(clean) === -1) return null;
  return clean;
};
// Cloudinary overrides (managed from logoUpload.html).
// Maps team tag -> full image URL. Populated live from
// /live-graphics/logoOverrides; local img/logos/ stays the fallback.
window.LOGO_URLS = window.LOGO_URLS || {};
function ensureLogoOverrideListener() {
  if (ensureLogoOverrideListener.done) return;
  try {
    if (typeof firebase === "undefined" || !firebase.apps || !firebase.apps.length || !firebase.database) return;
    ensureLogoOverrideListener.done = true;
    firebase.database().ref("/live-graphics/logoOverrides").on("value", function(snap) {
      window.LOGO_URLS = snap.val() || {};
    });
  } catch (e) {}
}
window.logoUrl = function(tag) {
  ensureLogoOverrideListener();
  var clean = String(tag).trim().replace(/[^a-zA-Z0-9_-]/g, "").toLowerCase();
  if (!clean) return null;
  var entry = window.LOGO_URLS[clean];
  if (typeof entry === "string" && entry) return entry;
  if (!entry || typeof entry !== "object") return null;
  var u = entry.url;
  return (typeof u === "string" && u) ? u : null;
};
