// AUTO-GENERATED by logos.py - do not edit by hand. Re-run logos.py after adding/removing files in img/logos/.
window.LOGO_TAGS = ["a7", "ae", "bb", "be", "brb", "cu", "gs", "inp", "lt", "mvp", "ne", "tux"];
window.logoFile = function(tag) {
  var clean = String(tag).trim().replace(/[^a-zA-Z0-9_-]/g, "").toLowerCase();
  if (!clean || window.LOGO_TAGS.indexOf(clean) === -1) return null;
  return clean;
};
