// Generates js/config.js from .env (local dev) or process.env (Vercel).
// Usage (local, required once before opening pages via file://):
//   node build-config.js
// Vercel: set Build Command to `node build-config.js` and add the same
// keys as Environment Variables (they override .env values).
// The generated js/config.js is gitignored — never commit it.
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const ENV_PATH = path.join(ROOT, ".env");
const OUT_PATH = path.join(ROOT, "js", "config.js");

function loadEnvFile(p) {
  const out = {};
  if (!fs.existsSync(p)) return out;
  fs.readFileSync(p, "utf8").split(/\r?\n/).forEach(function (line) {
    const t = line.trim();
    if (!t || t[0] === "#") return;
    const i = t.indexOf("=");
    if (i < 0) return;
    out[t.slice(0, i).trim()] = t.slice(i + 1).trim();
  });
  return out;
}

const fileEnv = loadEnvFile(ENV_PATH);
function v(name) {
  if (process.env[name] !== undefined && process.env[name] !== "") return process.env[name];
  return fileEnv[name] || "";
}

const required = [
  "FIREBASE_API_KEY", "FIREBASE_AUTH_DOMAIN", "FIREBASE_DATABASE_URL",
  "FIREBASE_PROJECT_ID", "FIREBASE_STORAGE_BUCKET",
  "FIREBASE_MESSAGING_SENDER_ID", "FIREBASE_APP_ID",
  "CASTER_FIREBASE_API_KEY", "CASTER_FIREBASE_AUTH_DOMAIN",
  "CASTER_FIREBASE_DATABASE_URL", "CASTER_FIREBASE_PROJECT_ID",
  "CASTER_FIREBASE_STORAGE_BUCKET", "CASTER_FIREBASE_MESSAGING_SENDER_ID",
  "CASTER_FIREBASE_APP_ID", "OPERATOR_PIN", "SHEETS_WEBAPP_URL"
];
const missing = required.filter(function (k) { return !v(k); });
if (missing.length) {
  console.error("build-config.js: missing required values: " + missing.join(", "));
  process.exit(1);
}

const cfg = {
  firebase: {
    apiKey: v("FIREBASE_API_KEY"),
    authDomain: v("FIREBASE_AUTH_DOMAIN"),
    databaseURL: v("FIREBASE_DATABASE_URL"),
    projectId: v("FIREBASE_PROJECT_ID"),
    storageBucket: v("FIREBASE_STORAGE_BUCKET"),
    messagingSenderId: v("FIREBASE_MESSAGING_SENDER_ID"),
    appId: v("FIREBASE_APP_ID")
  },
  casterFirebase: {
    apiKey: v("CASTER_FIREBASE_API_KEY"),
    authDomain: v("CASTER_FIREBASE_AUTH_DOMAIN"),
    databaseURL: v("CASTER_FIREBASE_DATABASE_URL"),
    projectId: v("CASTER_FIREBASE_PROJECT_ID"),
    storageBucket: v("CASTER_FIREBASE_STORAGE_BUCKET"),
    messagingSenderId: v("CASTER_FIREBASE_MESSAGING_SENDER_ID"),
    appId: v("CASTER_FIREBASE_APP_ID")
  },
  operatorPin: v("OPERATOR_PIN"),
  sheetsWebappUrl: v("SHEETS_WEBAPP_URL")
};

const js = "// GENERATED by build-config.js — do not edit. Source: .env / environment.\n" +
  "window.TMR_CONFIG = " + JSON.stringify(cfg, null, 2) + ";\n";
fs.writeFileSync(OUT_PATH, js, "utf8");
console.log("build-config.js: wrote " + OUT_PATH);
